### PR TITLE
Add separate profiles xml for mesh communication

### PR DESCRIPTION
**Pull request by jnippula**
Mesh topics shall keep messages in history so durability qos shall not be volatile. This is because drones can leave and join mesh dynamically and important topics shall be available for new drones also.

### CODE REVIEW

**Comment by maseabunikie** [comment]
When and where setup_ros_profiles.sh script is used?

**Comment by maseabunikie** [comment]
I can see three different profiles. How are they used? The service files use the setup_fog.sh script which always uses the default profile.

**Comment by jnippula** [comment]
> I can see three different profiles. How are they used? The service files use the setup_fog.sh script which always uses the default profile.

Removed unnecessary one, because the topic qos settings can be change in the node code, so no need for separate xml for each topic qos settings.
So there are two different xml files. One is for default local communication and one for communication over mesh network. The app can define profile env variable before creating the ROS2 node object, which then loads the configuration into use. The only way change network interface whitelisting for ROS2 nodes is the profile xml file, so we need two separate xml files for local and mesh com. To avoid local topics bein visible over mesh, the mesh comm profile shall prevent local communication. The idea is that the app that shall communicate both local and mesh ROS network shall create two different nodes with different profiles (local and mesh)

**Comment by maseabunikie** [comment]
Thanks for the clear explanation!!
Very smart solution!

**Review by maseabunikie — APPROVED** [review]

**Pull request merged**
